Image: "fabric8/exposecontroller"
ImageTag: "2.3.34"
Annotations: {}
Args: [--help]

# To use exposecontroller you probably want to enable it in helm hooks, here's an example values.yaml:

# expose:
#   annotations:
#     helm.sh/hook: post-install
#     helm.sh/hook-delete-policy: hook-succeeded
#   # add custom domain here else defaults to using nip.io if a single node cluster
#   args: [--domain, "", --exposer, "Ingress", --http, "true"]

# cleanup:
#   annotations:
#     helm.sh/hook: pre-delete
#     helm.sh/hook-delete-policy: hook-succeeded
#   args: [--cleanup]